### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by shiffman** [shiffman/OpenKinect-for-Processing#13]
Now that I am using JNA this should be pretty easy and just involves getting the libfreenect DLLs as well as updating `LibraryPath.java`.

**Comment by ThomasLengeling** [comment]
Kinect v2 working on windows on the branch vc2013, tomorrow I'll tested on a fresh pc and I'll merge to the master branch.

I did not have any issues with the LibraryPath.java on Windows, I just added the .libs and .dll inside the native library folder and everything links automatically. 

I suggest adding three new folders inside the library folder; msvc, mac and linux

**Comment by ThomasLengeling** [comment]
both v1 and v2 has windows support.
