### ISSUE TITLE
use of openkinect library on windows 

### ISSUE THREAD

**Issue by Goodvirus** [shiffman/OpenKinect-for-Processing#132]
hello,
  can i use this libraty on microsoft windows 10?

**Comment by Goodvirus** [comment]
it can be used by installing libusbk library

**Comment by ghost** [comment]
Hi,
can you tell me what library did you install?
I'm trying for a long time and gets this error all the time both on windows 10 and ubuntu:
libusb error -12: LIBUSB_ERROR_NOT_SUPPORTED

Thanks

**Comment by Goodvirus** [comment]
Hello itzku,
         I am assuming that you are using kinect sdk. But openkinect library uses different drivers ( libfreenect2) to access kinect data. So for that you have to first uninstall kinect sdk and install libusbK drivers.
        For more information on installing drivers you can refer following page: 
https://github.com/OpenKinect/libfreenect2/blob/master/README.md#windows--visual-studio
I hope this will help you.
