### ISSUE TITLE
Multiple kinects

### ISSUE THREAD

**Issue by shiffman** [shiffman/OpenKinect-for-Processing#17]
The library currently can tell you how many kinects are connected and you can select one, but using more than one isn't really supported.  Need to fix this.

**Comment by ThomasLengeling** [comment]
hey, I can look into this, the v2 can handle now multiple Kinects

**Comment by shiffman** [comment]
Awesome, thanks!

**Comment by ThomasLengeling** [comment]
added multi kinect v1 example, tested with two kinect v1!!

Going to pimp up the example

8820b4e18d43d806df2409216d6505c0fe6da90f

**Comment by shiffman** [comment]
Awesome, fantastic, thank you!  Feel free to close this issue when completed.
