### ISSUE TITLE
32-bit  error Mac OS X

### ISSUE THREAD

**Issue by nicocaporohde** [shiffman/OpenKinect-for-Processing#2]
A library relies on native code that's not available.
Or only works properly when the sketch is run as a 64-bit  application.

And same error when force to 32 bit.

Is this a problem with Java 7 which only works in 64 bits?

**Comment by openthy** [comment]
Has anyone managed to make OpenKinect work with Kinect 1473 and Processing? 

I've done all the steps described here and many others described everywhere else on internet. The furthest I got was making the kinect work through terminal and glview. Which means it works, but still, non of the Processing versions would see it neither with the latest OpenKinect library, nor the SimpleOpenNI one. What I managed to find was a hacked version of the SimpleOpenNI library for 1473 that does work with Processing (tried in 3.0a4), here is a working link:
http://medienlabor.hs-osnabrueck.de/download/SimpleOpenNI_1.96_osx_kinect_1473.zip

Download and replace your existing library with this one and the magic will happen. I guess there should be a way to make the OpenKinect library work with 1473 too. 

My setup: OSX Yosemite (10.10.1), Kinect 1473, Processing 3.0a4 / 2.2.1.

**Comment by rrazor** [comment]
@openthy Thank you for that link—just what I needed. The SimpleOpenNI examples work for me in Processing 3.0a5. Was [this simple-openni-discuss thread](https://groups.google.com/forum/#!msg/simple-openni-discuss/JdVyOh8k7-Y/Bc3FmwWazkUJ) where you found it?

**Comment by openthy** [comment]
Hey @rrazor, no worries. I found the link elsewhere on the web, but looks like it originated from that post. So thanks to Sebastian Moeller for that one!

**Comment by fwasim** [comment]
Has anyone been able to run this on a Linux? I know this library was meant for a Mac, but there are tutorials out there, albeit outdated, where people have run it on Linux. 

I have installed it on my Linux, but now I am seeing this exact same error message on it. I have installed the latest version of libusb using linuxbrew (although there exists an older version of libusb on the system). My system is an Ubuntu 14.04 and processing 2.2.1. Any help would be greatly appreciated.

**Comment by TDA2030** [comment]
help ..
In the library SimpleOpenNI, is not present depthscene. I tried again to download last version, but still nothing.
But how could eliminate the line of perspective, on the window kinect?
thanks in advace*

![schermata 2015-02-08 alle 15 52 10](https://cloud.githubusercontent.com/assets/10909400/6097027/f5c2a8ca-afac-11e4-9555-c249e4f35b98.png)

**Comment by DelaramK** [comment]
"A library relies on native code that's not available.
Or only works properly when the sketch is run as a 32-bit  application."
on mac Yosemite, can this be fixed?

**Comment by p-cat** [comment]
Any one have any luck resolving this 32bit error ? running on win7 64 here

**Comment by NadaCat** [comment]
After little over a year (sorry, working on so many different art projects) - I got it to work using the instructions here. Thank you.

**Comment by shiffman** [comment]
With the new release this issue should *finally* be resolved.  Please test and open new issues!

https://github.com/shiffman/OpenKinect-for-Processing/releases/tag/0.3a1
