### ISSUE TITLE
kinect v2 raw depth data

### ISSUE THREAD

**Issue by shiffman** [shiffman/OpenKinect-for-Processing#21]
The v1 kinect raw depth data range is 0 - 2048, as seen in [the v1 examples](https://github.com/shiffman/OpenKinect-for-Processing/tree/master/OpenKinect-Processing/examples/Kinect_v1).

* What is the raw depth data range for kinect v2?
* How do the v2 depth values map to distance for thresholding and point clouds?

The answers to these questions will provide the fixes for:

* [point cloud v2](https://github.com/shiffman/OpenKinect-for-Processing/blob/master/OpenKinect-Processing/examples/Kinect_v2/PointCloud2/PointCloud2.pde)
* [depth threshold v2](https://github.com/shiffman/OpenKinect-for-Processing/tree/master/OpenKinect-Processing/examples/Kinect_v2/DepthThreshold2/DepthThreshold2.pde)

**Comment by Velro** [comment]
Dimensions are 512 by 424, with depth values ranging from 0 to 8000mm

**Comment by ThomasLengeling** [comment]
I don't think the depth detects upto 8m. 

The ```getRawDepthData``` function return an array of ints from 0 - 4500mm

**Comment by ThomasLengeling** [comment]
The ```getRawDepthData``` is throwing  strange values, fixing.

**Comment by ThomasLengeling** [comment]
Fixed with f4f1c14e1bc642177a36069ac1a14a9a6e296795

**Comment by shiffman** [comment]
Awesome, going to close this issue and we can open new ones if there are more specific bugs with particular examples, etc.

**Comment by lisajamhoury** [comment]
For other people searching for this info. This is from the Kinect [SDK](https://docs.microsoft.com/en-us/previous-versions/windows/kinect/dn772983(v%3dieb.10)): 

> The data for this frame is stored as 16-bit unsigned integers, where each value represents the distance in millimeters. The maximum depth distance is 8 meters, although reliability starts to degrade at around 4.5 meters. Developers can use the depth frame to build custom tracking algorithms in cases where the IBodyFrame isn’t enough.

Eight meters would mean 0-8000, or 13-bit, which goes up to 8191, with reliability beginning to degrade at 4500.
