### ISSUE TITLE
Enables for Kinect v2

### ISSUE THREAD

**Issue by ThomasLengeling** [shiffman/OpenKinect-for-Processing#22]
include enables for each capture frame same as kinect v1?

startDepth()
startVideo()
startIR()
startRegistered()

**Comment by ThomasLengeling** [comment]
as well as

toggleVideo()
toggleDepth()
toggleIR()

**Comment by ThomasLengeling** [comment]
Enables working with 02caf004538433958e8e8c109b81f4dd11847bcb

**Comment by shiffman** [comment]
Thanks for this.  I'm not married to the particular functions and their names at all.  I made some very arbitrary decisions.  Back when I made the first Kinect library being able to process only, say, the depth had significant performance benefits.  But testing now, everything seems to just run so fast even with everything going.  

If you have better ideas for how to name / organize the methods I'd love to hear them. (For example, with v1, I find the the `setIR()` and `setColorDepth()` methods a bit awkward.)

**Comment by ThomasLengeling** [comment]
change the naming check the branch rectacto_naming, updated all the examples

**Comment by shiffman** [comment]
This looks great to me!  What about removing the toggle functions and not having the functionality in the examples where the depth and video images can stopped and started?  This seems like no one will every use this functionality?

**Comment by ThomasLengeling** [comment]
sure I can remove the toggle functions

**Comment by ThomasLengeling** [comment]
Do I remove the stopDepth(), and stopVideo() functions?

**Comment by shiffman** [comment]
I think we should leave the various `stop()` methods but not include them as a key aspect of documentation/examples.

**Comment by shiffman** [comment]
All set now, thanks @ThomasLengeling !
