### ISSUE TITLE
Which Release to Test?

### ISSUE THREAD

**Issue by brendanmatkin** [shiffman/OpenKinect-for-Processing#24]
@shiffman I have a brand new mbp w/ Yosemite 10.10.4 and a model 1414 Kinect. Just downloading processing 3.0a11. I haven't downloaded any version of this library yet, or any libusb files or anything like that. Haven't installed any kinect SDKs. Haven't installed homebrew or macports yet. 

Would it be helpful for me to test a specific release?

**Comment by shiffman** [comment]
Great!  Please try the latest: https://github.com/shiffman/OpenKinect-for-Processing/releases/tag/0.3a5
