### ISSUE TITLE
It doesn't find the library, but it is there!

### ISSUE THREAD

**Issue by rossanag** [shiffman/OpenKinect-for-Processing#29]
Hi, I am running this library on Ubuntu 12.04, with Kinect 1414. I have  libfreenect installed also.
I've installed the library as any others I've installed before in P5, I know how to respect the folder structure. However when I try to run any of the library's examples I got the following messages:

A library relies on native code that's not available.
Or only works properly when the sketch is run as a 32-bit  application.

At  kinect.start();

I appreciate any hint. Thanks so much.
Best!

**Comment by ThomasLengeling** [comment]
Currently the library does not support Linux, only Mac with a Kinect v1

**Comment by rossanag** [comment]
Oh my bad, thanks for explanation.
