### ISSUE TITLE
Windows and 1473

### ISSUE THREAD

**Issue by coolbasha** [shiffman/OpenKinect-for-Processing#3]
Mr. shiffman... just wana start by saying that am one of your biggest fans, you never fail to amaze me and i have benefited a lot from your work.
Now I was wondering if this library would work with windows 7.
I also wanted know when u will be able to make this available to work with the kinect 1473 model. Need it urgentlllyyyyyy.

**Comment by shiffman** [comment]
Closing this issue, will open a new one re: windows support.
