### ISSUE TITLE
A library relies on native code that's not available. Or only works properly when the sketch is run as a 32-bit  application.

### ISSUE THREAD

**Issue by ewelinka** [shiffman/OpenKinect-for-Processing#30]
Hi!
I just downloaded Processing 3.0 beta 1 (6 August 2015) and by Sketch -> Import library -> Add library.. I installed OpenKinect. With the first sketch RGBDepthTest I already got this error message:

A library relies on native code that's not available.
Or only works properly when the sketch is run as a 32-bit  application.

I'm on OS X Yosemite.

**Comment by ThomasLengeling** [comment]
hey try using this release:

https://github.com/shiffman/OpenKinect-for-Processing/releases/tag/0.3a5

**Comment by shiffman** [comment]
Sorry everyone, I'm just catching up. . will be responding to issues and get a release out to Processing 3 this weekend.

**Comment by shiffman** [comment]
See #31
