### ISSUE TITLE
AveragePointTracking2 Example Issue

### ISSUE THREAD

**Issue by Lachie9383** [shiffman/OpenKinect-for-Processing#32]
I am getting weird behaviour with theAveragePointTracking2 example and seen in the screenshot below.  

<img width="642" alt="screen shot 2015-08-11 at 5 31 56 pm" src="https://cloud.githubusercontent.com/assets/7246955/9190901/358407e6-404f-11e5-89b2-d949bb39844c.png">

I'm also receiving this error in the console:

[DepthPacketStreamParser::onDataReceived] not all subsequences received 0
[DepthPacketStreamParser::onDataReceived] not all subsequences received 896

Any idea what's happening?

**Comment by ThomasLengeling** [comment]
this code should work

https://github.com/shiffman/OpenKinect-for-Processing/tree/refacto_naming/OpenKinect-Processing/examples/Kinect_v2/AveragePointTracking2

however, the initDepth(), and initDevice() naming should be for you startDepth and startDevice I believe

**Comment by ThomasLengeling** [comment]
hey!.

check the new release, that example should be working

https://github.com/shiffman/OpenKinect-for-Processing/releases/tag/0.3a6

**Comment by shiffman** [comment]
Closing, @Lachie9383 please feel free to test the new release.
