### ISSUE TITLE
Ready to merge refacto_naming branch

### ISSUE THREAD

**Issue by ThomasLengeling** [shiffman/OpenKinect-for-Processing#33]
New release with the refacto_naming branch.
https://github.com/shiffman/OpenKinect-for-Processing/tree/refacto_naming

Release 
https://github.com/shiffman/OpenKinect-for-Processing/releases/tag/0.3a6

changes include

- Kinect v1 and Kinect v2 windows and mac support.
- Renaming methods from startDepth to initDepth similar for the other frames.
- Faster point cloud evaluation for v1, new Point cloud openGL example
- New point cloud examples for v1 and v2.
- All examples tested
- Mirror mode.

**Comment by shiffman** [comment]
Yes, go ahead and merge!   I keep holding off on updating the official release since I'd like to finish off the documentation, but I think I should go ahead.  Merge and I'll make a release and alert @prisonerjohn.

**Comment by ThomasLengeling** [comment]
ok, got the linux version working for v1!

**Comment by shiffman** [comment]
wow, awesome!

**Comment by ThomasLengeling** [comment]
but have to do sudo ./processing to get it activated/. any idea how to do a work around it?, i tried doing 
"chmod 777 libfreenect.so" but no luck.

**Comment by shiffman** [comment]
Sadly, I have no linux experience here.  I wonder if @codeanticode might have any tips?

**Comment by shiffman** [comment]
I am closing this, a separate issue can be opened to track linux.
