### ISSUE TITLE
Kinect 1473 not detect

### ISSUE THREAD

**Issue by sabas1080** [shiffman/OpenKinect-for-Processing#37]
I installed the SDK drivers and processing 3.0b4 error

"64 windows
There are no kinects, returning null"

Thanks

**Comment by ThomasLengeling** [comment]
Did you change the you change the kinect drivers to libusbK?

**Comment by sabas1080** [comment]
I change driver zadig and detect kinect, but not work examples

**Comment by sabas1080** [comment]
Thanks reinstall driver for libusbK and work, Kinect 1473 work
