### ISSUE TITLE
Cannot use libfreenect driver as non-root?

### ISSUE THREAD

**Issue by cliff76** [shiffman/OpenKinect-for-Processing#40]
I just installed libfreenect via Homebrew and realized I need to be root to the freenect-glview program to test my install. (I get "Number of devices found: 0" when I run as non-root.) I then tried installing this processing plugin and running a hello world sketch. The sketch give an error, "No Kinect devices found." I'm assuming this means I have to run the process as a root user. I saw instructions on the openkinect.org wiki explaining how to access the Kinect as a non-root user on Linux but I see no OS X equivalent. Do you know how to resolve the issue?

**Comment by shiffman** [comment]
This library should work on OSX as any user.  I should also note it requires no separate install of libfreenect as that is bundled with this library.
