### ISSUE TITLE
Kinect2 - Depth as RGB.

### ISSUE THREAD

**Issue by philspitlerSF** [shiffman/OpenKinect-for-Processing#44]
I am having trouble get the depth as RGB in the Kinect2 Library.

I am trying.

kinect2.enableColorDepth(true);

Which I believe should work but just errors.

Any idea?

**Comment by ThomasLengeling** [comment]
what are the errors?, system?
I think enableColorDepth is only for the kinect v1

**Comment by philspitlerSF** [comment]
I get the error:

enableColorDepth(boolean) does not exist.

Thanks

OSX 10.10.5 
Processing 3.0
