### ISSUE TITLE
Mention that they might need to install libusb

### ISSUE THREAD

**Issue by golanlevin** [shiffman/OpenKinect-for-Processing#5]
I was working on a newish machine and OpenKinect didn't work; the error (which might be opaque to a noob) was that libusb was not installed. I had to install macports, in order to install libusb, in order for libfreenect to work within OpenKinect for Processing. It may be worth mentioning this in the installation instructions.

**Comment by shiffman** [comment]
This is *finally* in progress!  I have an updated version of the library using the latest libfreenect.  I will be posting an easy to download/test release soon for testing.  The next step will be incorporating libfreenect2 for the newest Kinects as well. Stay tuned!

**Comment by shiffman** [comment]
This should no longer be the case with the new release!

https://github.com/shiffman/OpenKinect-for-Processing/releases/tag/0.3a1

I'm sure there will be new issues and problems like this one.  But I'm closing this now that I have rebuilt the library from scratch with current libfreenect!  Please test and file new issues!
