### ISSUE TITLE
getRegisteredImage() for Kinect v1?

### ISSUE THREAD

**Issue by y-sira** [shiffman/OpenKinect-for-Processing#53]
We are developing a Kinect app for university's assignment.

There is a gap between depth image and RGB image, so we tried to fix it.
I found the API "getRegisteredImage()" but it is available for Kinect v2.
How can I fix this problem?

Incidentally, If you know the library which provides skeleton tracking, please teach me.

Thank you.

**Comment by ThomasLengeling** [comment]
Hello, getRegisteredImage() is only available for the Kinect v2, due that the libfreenect library does not provide a equivalent function. 
You can also check the simpleOpenNI library.
