### ISSUE TITLE
Control Leds?

### ISSUE THREAD

**Issue by itachi97440** [shiffman/OpenKinect-for-Processing#58]
Hi,

Can I control RGB Leds Strip with Your Library on Processing?

**Comment by AndreasRef** [comment]
Hi itachi97440 

I am actually working on a project, where I am controlling RGB Led Strips with a Kinect as an input. The OpenKinect library in itself does not allow you to control RGB light strips, so in my case I am using the [Pixel Pusher Library] (https://github.com/robot-head/PixelPusher-processing).

I hope to publish some of the code on my GitHub within the next month or two, so keep an eye out for it if you want to.

Cheers

**Comment by shiffman** [comment]
This library is for the MS Kinect only.
