### ISSUE TITLE
DepthPointCloud2 error

### ISSUE THREAD

**Issue by MrfksIv** [shiffman/OpenKinect-for-Processing#59]
When i try to run the DepthPointCloud2 i get the exception "CameraParams cannot be resolved to a variable. 
The problem seems to be at the depthToPointCloudPos method, specifically at:

`point.x = (x - CameraParams.cx) * point.z / CameraParams.fx;
  point.y = (y - CameraParams.cy) * point.z / CameraParams.fy;`

Can anyone help?
Thanks

**Comment by ThomasLengeling** [comment]
you need to have the adicional tab/code of CameraParams

**Comment by metaColin** [comment]
I think this is what you need:

//camera information based on the Kinect v2 hardware
static class CameraParams {
  static float cx = 254.878f;
  static float cy = 205.395f;
  static float fx = 365.456f;
  static float fy = 365.456f;
  static float k1 = 0.0905474;
  static float k2 = -0.26819;
  static float k3 = 0.0950862;
  static float p1 = 0.0;
  static float p2 = 0.0;
}
