### ISSUE TITLE
KinectTracker not recognized

### ISSUE THREAD

**Issue by kellyvigil** [shiffman/OpenKinect-for-Processing#7]
I've got both open Kinect for processing and simple and  simpleOpenNI but I can't run your code for Average Point Tracker on http://shiffman.net/p5/kinect/ . I've got the point cloud to work, but when I run A.P.T. processing says "cannot find a class or type named "kinectTracker".

How can I fix this?

**Comment by shiffman** [comment]
The library is revamped and completely new.  Try the new examples!

https://github.com/shiffman/OpenKinect-for-Processing/releases/tag/0.3a1
