### ISSUE TITLE
Isochronous transfer error: 1

### ISSUE THREAD

**Issue by uraeu5** [shiffman/OpenKinect-for-Processing#73]
I'm using a kinect v1 1414, installed the SDK and installed the libusbK drivers, but whenever I run any of the example files with the open kinect for processing library I get "Isochronous transfer error: 1"  and the sketch freezes.  Any ideas how to solve this?  Much thanks.

**Comment by laurage** [comment]
Same here.
I'm on Windows 10.

**Comment by laurage** [comment]
Did you find any fix?

**Comment by laurage** [comment]
Update: Every time I was turning the computer off, it stopped working again.

Solution:
The drivers must be desinstalled in the Windows manager
+ Use windows clean disk to clear the remaining traces of the drivers!
Then reinstall the drivers with Zadig.

**Comment by huangy10** [comment]
Same problem here, on macOS. But situation is a little different here. When I start the program, the kinect works fine at the beginning. But after running for a while, there is a chance that the sketch stops and the error messages shows up (not always). I cant figure out why.

**Comment by jonnyscholes** [comment]
This link is useful to those having this issue that came here via Google: https://groups.google.com/forum/#!topic/openkinect/3z8-4xIUXf8

**Comment by candanerim** [comment]
Hi, I met the same error "Isochronous transfer error: 1" when I tried to run Shiffman's [https://github.com/shiffman/OpenKinect-for-Processing/tree/master/OpenKinect-Processing/examples/Kinect_v1/AveragePointTracking] example code for Kinect. I have Kinect v1 1473 and Windows 10 and downloaded drivers with Zadig. I searched the forums, there are so many people who met this error but still couldn't fix. If you find a solution please let me know.

**Comment by jnydutra** [comment]
Downgrade libusbK worked for me. Use http://zadig.akeo.ie/downloads/zadig_2.0.1.exe on windows.
