### ISSUE TITLE
No Kinect Devices Found OSX el capitan

### ISSUE THREAD

**Issue by aliceEddie** [shiffman/OpenKinect-for-Processing#76]
I'm having an issue with the library. 
I'm using a Kinect Model 1414 and when I'm trying to run a sketch I get the error:

> No Kinect devices found.
> Failed to open camera subdevice or it is not disabled.Failed to open audio subdevice or it is not disabled.There are no kinects, returning null
> 

Couldn't find any solution for this so far. 
Any help is greatly appreciated!

Edit:

Solution was rather easy, the outlet the kinect was plugged into was switched off. 
LED was still blinking but it only showed the NUI Motor.

**Comment by aliceEddie** [comment]
Solution was rather easy, the outlet the kinect was plugged into was switched off. 
T

**Comment by shiffman** [comment]
glad to hear!

**Comment by EvelynGiron** [comment]
Hello @aliceEddie can you explain me step by step this? I have the same problem and i speak spanish I can´t understand. Please I have 2 months trying make works the kinect with El Capitan en Mac, always is the same: No Kinect Devices Found.

**Comment by aliceEddie** [comment]
Hi @EvelynGiron 

I'm sorry I don't speak Spanish, I'll explain it in English, just ask if anything is unclear.

my problem was really simple:
I didn't plug the power cable in properly.
The USB was connected but not the power cable.

Can you try the Kinect on a different computer?

Does the Kinect show up in your system report? 
Connect the Kinect to your computer. Click on the apple logo in the top left corner, then on "about this mac", it will give you information about your mac and on the bottom it should say "system report"

![Image of Report](https://support.apple.com/library/content/dam/edam/applecare/images/en_US/osx/mbp-el-cap-about-this-mac-build-number.png)

Now look for USB (under Hardware), and you will get a list of all connected USB devices. Does the Kinect show up?

**Comment by EvelynGiron** [comment]
THANK YOU @aliceEddie for you explanation, isn´t matter that was in English. The USB shows as XBOX NIU Motor… LED was still blinking. I have  a question: the green light of your adapter is lit ? , I think maybe the adapter is not working. 
This is more difficult than it should be. 

![captura de pantalla 2016-09-01 a las 8 21 32 p m](https://cloud.githubusercontent.com/assets/21698317/18226767/3cd30216-71ce-11e6-9d5f-c32c6afdea5d.png)
![captura de pantalla 2016-09-03 a las 12 01 00 p m](https://cloud.githubusercontent.com/assets/21698317/18226778/6120f29a-71ce-11e6-8b1c-54661364a49b.png)
