### ISSUE TITLE
setMirror() equivalent in OpenKinect

### ISSUE THREAD

**Issue by HardScience** [shiffman/OpenKinect-for-Processing#8]
I'd like to do skeleton tracking, but it appears as though the latest version of Simple-OpenNI (1.96) does not support setMirror. It turns out that OpenKinect for Processing does not have an equivalent to the Simple-openNI function setMirror(). It would be great to have that feature available in the OpenKinect library! And then hopefully I'll be able to make use of Simple-OpenNI's skeleton tracking ability and OpenKinect for setting the mirror, along with other features not supported by Open-SimpleNI. I'm running SDK 1.8, Processing 2.2.1, Simple-OpenNI 1.96, Win 7-64.

**Comment by shiffman** [comment]
@ThomasLengeling do you want to take a crack at this one?

**Comment by ThomasLengeling** [comment]
the new release has a mirror method.
